force-app/main/default/objects/Account/fields/Apex_Record_Creation_History_Status__c.field-meta.xml
<CustomField>
    <fullName>Apex_Record_Creation_History_Status__c</fullName>
    <description>Shows the status of creating a Record Creation History for an Account using Queueable Apex. Pending means that it should be running and complete soon.</description>
    <inlineHelpText>Shows the status of creating a Record Creation History for an Account using Queueable Apex. Pending means that it should be running and complete soon.</inlineHelpText>
    <label>Apex Record Creation History Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Async_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Apex_UUID_Status__c.field-meta.xml
<CustomField>
    <fullName>Apex_UUID_Status__c</fullName>
    <description>Shows the status of setting Account.AccountNumber to a UUID using Queueable Apex. Pending means that it should be running and complete soon.</description>
    <inlineHelpText>Shows the status of setting Account.AccountNumber to a UUID using Queueable Apex. Pending means that it should be running and complete soon.</inlineHelpText>
    <label>Apex UUID Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Async_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Async_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>Running</fullName>
        <isActive>false</isActive>
        <label>Running</label>
    </customValue>
    <masterLabel>Async Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountQueueableHandler.cls
/**
 * @author aidan@nebulaconsulting.co.uk
 * @date 22/05/2023
 * @description Handles querying and iteration to simplify the Queueables that process Account records
 */

public abstract inherited sharing class AccountQueueableHandler implements Queueable {

    // Use a list here not an iterator because the iterator returned from a Set<Id> d
    private List<Id> accountsToProcess;

    public AccountQueueableHandler(Set<Id> accountsToProcess) {
        this.accountsToProcess = new List<Id>(accountsToProcess);
    }

    public void execute(QueueableContext qc) {
        Id thisAccountId = accountsToProcess.remove(0);
        Account thisAccount = [
                SELECT Id, AccountNumber, CreatedById, CreatedDate,
                        Apex_UUID_Status__c, Apex_Record_Creation_History_Status__c
                FROM Account
                WHERE Id = :thisAccountId
        ];

        execute(thisAccount.clone(true, true, true));

        if(!accountsToProcess.isEmpty()) {
            if(Test.isRunningTest()) {
                execute(qc);
            } else {
                System.enqueueJob(this);
            }
        }
    }

    abstract void execute(Account theAccount);
}