force-app/main/default/objects/Account/fields/Apex_Record_Creation_History_Status__c.field-meta.xml
<CustomField>
    <fullName>Apex_Record_Creation_History_Status__c</fullName>
    <description>Shows the status of creating a Record Creation History for an Account using Queueable Apex. Pending means that it should be running and complete soon.</description>
    <inlineHelpText>Shows the status of creating a Record Creation History for an Account using Queueable Apex. Pending means that it should be running and complete soon.</inlineHelpText>
    <label>Apex Record Creation History Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Async_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Apex_UUID_Status__c.field-meta.xml
<CustomField>
    <fullName>Apex_UUID_Status__c</fullName>
    <description>Shows the status of setting Account.AccountNumber to a UUID using Queueable Apex. Pending means that it should be running and complete soon.</description>
    <inlineHelpText>Shows the status of setting Account.AccountNumber to a UUID using Queueable Apex. Pending means that it should be running and complete soon.</inlineHelpText>
    <label>Apex UUID Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Async_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Automation_Type__c.field-meta.xml
<CustomField>
    <fullName>Automation_Type__c</fullName>
    <label>Automation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Automation_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Async_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>Running</fullName>
        <isActive>false</isActive>
        <label>Running</label>
    </customValue>
    <masterLabel>Async Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Automation_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Synchronous Apex</fullName>
        <default>true</default>
        <label>Synchronous Apex</label>
    </customValue>
    <customValue>
        <fullName>Asynchronous Apex</fullName>
    </customValue>
    <customValue>
        <fullName>Asynchronous Flow</fullName>
    </customValue>
    <masterLabel>Automation Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountSetApexAsyncPending.cls
/**
 * @author aidan@nebulaconsulting.co.uk
 * @date 22/05/2023
 * @description Sets the Async Apex Status fields (Apex_Record_Creation_History_Status__c and Apex_UUID_Status__c) to
 * pending if Automation_Type__c is 'Asynchronous Apex'
 */

global without sharing class AccountSetApexAsyncPending implements nebc.BeforeInsert {
    public void handleBeforeInsert(List<Account> newList) {
        new nebc.LazySObjectIterator(newList)
                .filterOnField(Account.Automation_Type__c, 'Asynchronous Apex')
                .put(Account.Apex_Record_Creation_History_Status__c, 'Pending')
                .put(Account.Apex_UUID_Status__c, 'Pending')
                .forEach();
    }
}