force-app/main/default/objects/Account/fields/Apex_Record_Creation_History_Status__c.field-meta.xml
<CustomField>
    <fullName>Apex_Record_Creation_History_Status__c</fullName>
    <description>Shows the status of creating a Record Creation History for an Account using Queueable Apex. Pending means that it should be running and complete soon.</description>
    <inlineHelpText>Shows the status of creating a Record Creation History for an Account using Queueable Apex. Pending means that it should be running and complete soon.</inlineHelpText>
    <label>Apex Record Creation History Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Async_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_Creation_History__c/Record_Creation_History__c.object-meta.xml
<CustomObject>
    <label>Record Creation History</label>
    <nameField>
        <displayFormat>RCH-{0}</displayFormat>
        <label>Record Creation History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Creation Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_Creation_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Record Creation Histories</relationshipLabel>
    <relationshipName>Record_Creation_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Record_Creation_History__c/fields/Record_Created_By__c.field-meta.xml
<CustomField>
    <fullName>Record_Created_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Record Created By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Record_Creation_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Record_Creation_History__c/fields/Record_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Record_Created_Date__c</fullName>
    <label>Record Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/globalValueSets/Async_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>Running</fullName>
        <isActive>false</isActive>
        <label>Running</label>
    </customValue>
    <masterLabel>Async Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountRecordCreationHistoryQueueable.cls
/**
 * @author aidan@nebulaconsulting.co.uk
 * @date 17/05/2023
 * @description Creates a Record_Creation_History__c history for an inserted Account. Handles one Account per invocation
 */

public without sharing class AccountRecordCreationHistoryQueueable extends AccountQueueableHandler {

    public AccountRecordCreationHistoryQueueable(Set<Id> accountIds) {
        super(accountIds);
    }

    public void execute(Account thisAccount) {
        insert new Record_Creation_History__c(
                Record_Id__c = thisAccount.Id,
                Account__c = thisAccount.Id,
                Record_Created_By__c = thisAccount.CreatedById,
                Record_Created_Date__c = thisAccount.CreatedDate
        );

        thisAccount.Apex_Record_Creation_History_Status__c = 'Complete';
        update thisAccount;
    }
}