force-app/main/default/objects/Account/fields/Automation_Type__c.field-meta.xml
<CustomField>
    <fullName>Automation_Type__c</fullName>
    <label>Automation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Automation_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_Creation_History__c/Record_Creation_History__c.object-meta.xml
<CustomObject>
    <label>Record Creation History</label>
    <nameField>
        <displayFormat>RCH-{0}</displayFormat>
        <label>Record Creation History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Creation Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_Creation_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Record Creation Histories</relationshipLabel>
    <relationshipName>Record_Creation_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Record_Creation_History__c/fields/Record_Created_By__c.field-meta.xml
<CustomField>
    <fullName>Record_Created_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Record Created By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Record_Creation_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Record_Creation_History__c/fields/Record_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Record_Created_Date__c</fullName>
    <label>Record Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/globalValueSets/Automation_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Synchronous Apex</fullName>
        <default>true</default>
        <label>Synchronous Apex</label>
    </customValue>
    <customValue>
        <fullName>Asynchronous Apex</fullName>
    </customValue>
    <customValue>
        <fullName>Asynchronous Flow</fullName>
    </customValue>
    <masterLabel>Automation Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountRecordCreationHistory.cls
/**
 * @author aidan@nebulaconsulting.co.uk
 * @date 17/05/2023
 * @description Creates a Record_Creation_History__c history for an inserted Account
 */

global without sharing class AccountRecordCreationHistory implements nebc.AfterInsert {

    public static nebc.Function accountToRecordCreationHistory =
            new nebc.SObjectFromPrototype(new Record_Creation_History__c())
                    .putField(Record_Creation_History__c.Record_Id__c, Account.Id)
                    .putField(Record_Creation_History__c.Account__c, Account.Id)
                    .putField(Record_Creation_History__c.Record_Created_By__c, Account.CreatedById)
                    .putField(Record_Creation_History__c.Record_Created_Date__c, Account.CreatedDate);

    global void handleAfterInsert(List<Account> newList) {
        new nebc.LazySObjectIterator(newList)
                .filterOnField(Account.Automation_Type__c, 'Synchronous Apex')
                .mapValuesT(accountToRecordCreationHistory)
                .doInsert();
    }
}