force-app/main/default/objects/Account/fields/Automation_Type__c.field-meta.xml
<CustomField>
    <fullName>Automation_Type__c</fullName>
    <label>Automation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Automation_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_Creation_History__c/Record_Creation_History__c.object-meta.xml
<CustomObject>
    <label>Record Creation History</label>
    <nameField>
        <displayFormat>RCH-{0}</displayFormat>
        <label>Record Creation History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Creation Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_Creation_History__c/fields/Record_Created_By__c.field-meta.xml
<CustomField>
    <fullName>Record_Created_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Record Created By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Record_Creation_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Record_Creation_History__c/fields/Record_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Record_Created_Date__c</fullName>
    <label>Record Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/globalValueSets/Automation_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Synchronous Apex</fullName>
        <default>true</default>
        <label>Synchronous Apex</label>
    </customValue>
    <customValue>
        <fullName>Asynchronous Apex</fullName>
    </customValue>
    <customValue>
        <fullName>Asynchronous Flow</fullName>
    </customValue>
    <masterLabel>Automation Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountRecordCreationHistoryQueueTest.cls
/**
 * @author aidan@nebulaconsulting.co.uk
 * @date 22/05/2023
 */

@IsTest
private class AccountRecordCreationHistoryQueueTest {

    static nebc.TestRecordSource testRecordSource = new nebc.TestRecordSource();

    @IsTest
    static void testBehavior() {
        Test.startTest();
        Account testAccount = (Account)testRecordSource.getRecord(Account.SObjectType)
                .put(Account.Automation_Type__c, 'Asynchronous Apex')
                .withInsert();
        Test.stopTest();

        Record_Creation_History__c history = [
                SELECT Record_Id__c, Record_Created_By__c, Record_Created_Date__c
                FROM Record_Creation_History__c
        ];

        testAccount = [SELECT CreatedDate FROM Account WHERE Id = :testAccount.Id];

        Assert.areEqual(testAccount.Id, history.Record_Id__c);
        Assert.areEqual(testAccount.CreatedDate, history.Record_Created_Date__c);
        Assert.areEqual(UserInfo.getUserId(), history.Record_Created_By__c);
    }
}